resources:
  requests:
    cpu: 20m
    memory: 200Mi
  limits:
    memory: 1Gi

ingress:
  enabled: true
  type: internal
  rules:
  - hosts:
    - examples.dev.splitit.com
    paths:
    - /*
    port: https
