resources:
  requests:
    cpu: 50m
    memory: 300Mi
  limits:
    memory: 2Gi

hpa:
  minReplicas: 3
  maxReplicas: 6

ingress:
  enabled: true
  type: external
  rules:
  - hosts:
    - examples.production.splitit.com
    paths:
    - /*
    port: https

istio:
  hosts:
  - examples.production.splitit.com